# Generated by Django 3.2.9 on 2022-11-01 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=6, null=True)),
                ('group_name', models.CharField(max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject_name', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('professor_name', models.CharField(max_length=200, null=True)),
                ('professor_page_link', models.CharField(max_length=200, null=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row', to='Timetable_app.timetable')),
            ],
        ),
    ]
