# Generated by Django 3.2.9 on 2022-11-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
