# Generated by Django 3.2.9 on 2022-11-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable_app', '0002_alter_timetable_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablerow',
            name='rescheduled_info',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tablerow',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tablerow',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
